name: voracious
favicon: null
layout_spectrum: 0.16251454129815102
typography_spectrum: 0.22369760693982244
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00547c'
    - '#ffffff'
    - '#ffcf8b'
    - '#4e97b4'
    - '#775836'
  brandStrength: 0.1875
  lightness: 0.47188631282188
  saturation: 0.028611474437639117
  rhythmicContrast: 0.9722680621780455
purpose: []
